const STORAGE_NAME = '@gameplay';
const COLLECTION_USERS = `${STORAGE_NAME}:user`;
const COLLECTION_APPOINTMENTS = `${STORAGE_NAME}:appointments`;

export { COLLECTION_APPOINTMENTS, COLLECTION_USERS };
